// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG71wgyWMkq-nypOsz57fYJ7VUGYk76_w',
    appId: '1:625732856676:web:2bf44f247d9cb147aaa871',
    messagingSenderId: '625732856676',
    projectId: 'flutter-ecommerce-app-3dd32',
    authDomain: 'flutter-ecommerce-app-3dd32.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-3dd32.firebasestorage.app',
    measurementId: 'G-QTD8F6FKEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1EMb-VK94nqNm1lHM8Nl0bzLPJNoWb8',
    appId: '1:625732856676:android:d698b8efc2c826bbaaa871',
    messagingSenderId: '625732856676',
    projectId: 'flutter-ecommerce-app-3dd32',
    storageBucket: 'flutter-ecommerce-app-3dd32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrc4FRZ5dFXG8rFurd_7C2RsK_jeLup8Y',
    appId: '1:625732856676:ios:236f33c3000bbda1aaa871',
    messagingSenderId: '625732856676',
    projectId: 'flutter-ecommerce-app-3dd32',
    storageBucket: 'flutter-ecommerce-app-3dd32.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrc4FRZ5dFXG8rFurd_7C2RsK_jeLup8Y',
    appId: '1:625732856676:ios:236f33c3000bbda1aaa871',
    messagingSenderId: '625732856676',
    projectId: 'flutter-ecommerce-app-3dd32',
    storageBucket: 'flutter-ecommerce-app-3dd32.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG71wgyWMkq-nypOsz57fYJ7VUGYk76_w',
    appId: '1:625732856676:web:a78f3614ca141d40aaa871',
    messagingSenderId: '625732856676',
    projectId: 'flutter-ecommerce-app-3dd32',
    authDomain: 'flutter-ecommerce-app-3dd32.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-3dd32.firebasestorage.app',
    measurementId: 'G-86V7WYTH9Y',
  );
}
